name: Prisma Cloud Shift Left demo
on: [ push,pull_request ]

jobs:
  prisma_cloud_job:
    runs-on: ubuntu-latest
    name: Run Prisma Cloud steps 
    env:
          TL_USER: ${{ secrets.TL_USER }}
          TL_PASS: ${{ secrets.TL_PASS }}
          TL_CONSOLE: ${{ secrets.TL_CONSOLE }} 
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        

      - name: twistcli download
        run: curl -s -k -u $TL_USER:$TL_PASS "https://$TL_CONSOLE/api/v1/util/twistcli" -v -o twistcli;chmod +x twistcli

    
      - name: Scan Image for vulnerabilities
        run: bash ./files/scanImage.sh
   
      
      - name: Scan Image for Malware using Wildfire
        run: bash ./files/malwareCheck.sh
        
          
      #- name: Deploy evilpetclinic app
        #run: bash files/exec.sh deploy.sh
        
      #- name: Runtime attacks
        #run: bash files/exec.sh runtime_attacks.sh
          
      #- name: WAAS attacks
       # run: bash files/exec.sh waas_attacks.sh
